"""Crear tabla producto table

Revision ID: 63647b9676f3
Revises: ce8bd6bb6be6
Create Date: 2026-03-11 14:40:10.335461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63647b9676f3'
down_revision: Union[str, Sequence[str], None] = 'ce8bd6bb6be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
