"""Crear tabla con nueva extructura

Revision ID: e359ae9b81d5
Revises: fb4b15ef7fa1
Create Date: 2026-03-11 15:06:43.728923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e359ae9b81d5'
down_revision: Union[str, Sequence[str], None] = 'fb4b15ef7fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
